version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: truvi_db
    environment:
      POSTGRES_USER: truvi
      POSTGRES_PASSWORD: truvi123
      POSTGRES_DB: truvi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
